### ISSUE TITLE
Right prompts to upload long documents with ChatGPT free

### ISSUE THREAD

**Issue by theRAGEhero** [ariburaco/chatgpt-file-uploader-extended#7]
Hello and thank you for this plugin.

I have a document of 100 pages, and this is too much for the 2000 credits given with the free plan. I splitted the document in three parts and I'd like to know if someone has the right prompts to upload the three parts in a smooth way.

Thank you

**Comment by ariburaco** [comment]
we have improved the single and multi part prompts in v1.4. So, it should be work much better. and you can always set the chunk size (max. character size of each part) to find the right balance. 

But 100 page is to much for the ChatGPT, I suggest you to separate the document smaller pages like 10 page, and then use this extension to upload that 10 page parts. Because chatGPT has some message limits also.
